#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# print "Hello World!"

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > sudo /var/www/index.html
service nginx restart
